{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "restic-exporter.fullname" . }}
  labels:
    {{- include "restic-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ . | quote }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "restic-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
          targetLabel: instance
        {{- with .Values.serviceMonitor.relabelings }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
