apiVersion: v2
name: restic-exporter
description: Prometheus exporter for restic repositories
type: application
version: "2.0.2"
appVersion: "2.0.2"
kubeVersion: ">=1.25.0-0"
home: https://github.com/josh/restic-exporter
sources:
  - https://github.com/josh/restic-exporter
keywords:
  - restic
  - backup
  - prometheus
  - exporter
  - metrics
maintainers:
  - name: Joshua Peek
